title: autohugo
baseUrl: /autohugo/
params:
    description: auto-deployable static websites using hugo, the Github Pages and cicleci platform.
    copyright: The MIT License. - Copyright (c) 2015 Máximo Cuadros
    themeColor: "theme-base-0c"

menu:
  main:
      - Name: "Github project"
        Weight: 110
        URL: "https://github.com/mcuadros/autohugo"
